### ISSUE TITLE
64 bit program usage issues

### ISSUE THREAD

**Issue by Thunpe** [Wilenty/7zOverlay#2]
Hello，Wilenty
Thank you for providing the excellent 7zOverlay.dll tool for free.
This version is only applicable to 32-bit program calls，Not applicable for 64 bit program calls.

Consult if there is an x64 (64 bit) version available for 7z.dll，If there is (how much donation is required to obtain the x64 (64 bit) version suitable for 7z.dll).

**Comment by Wilenty** [comment]
Hello @Thunpe.
Sorry for late response, but now I have hard physical work, so I can check the messages only in the Sunday.

At the outset please edit first post and remove the email address from it, I have your email in my messages, so it's not need to be here.

```Thank you for providing the excellent 7zOverlay.dll tool for free.```
Thanks!
```This version is only applicable to 32-bit program calls，Not applicable for 64 bit program calls.```
Yes, for free I share only the 32-bit of this dll, especially for the InnoSetup based installers, because it has the lack of extracting other archives, excluding itself.

```Consult if there is an x64 (64 bit) version available for 7z.dll，If there is (how much donation is required to obtain the x64 (64 bit) version suitable for 7z.dll).```
(Probably) I have the 64-bit somewhere on the main computer, but it's old and it should be updated to the latest version, which takes the time.

If you saw, or not, I disabled all donation pages, because I don't have a time to check and share my products in the week. Also I need some free time time in the weekend to get the rest.

So, maybe for first we can talk here how much you would pay for the 64-bit version of 7zOverlay.dll? Then I will know if I should focus to update this dll to the latest version.
And I don't know if you want to use this dll personally or in corporation/office?

Greetings.
Wilenty

**Comment by Thunpe** [comment]
Hello, thank you for your reply
I plan to integrate this 7zOverlay.dll into a program for use, as there is no revenue source for this program.
DLLs can be encrypted and compressed before being built into the program. When called, memory runs without the need to decompress resources. This DLL will not be publicly shared.
Also, I don't know if it's possible to add a callback function to obtain the progress required.
In terms of donations: I wonder if 100 US dollars is possible
________________________________
发件人: Wilenty ***@***.***>
发送时间: 2023年6月19日 10:59
收件人: Wilenty/7zOverlay ***@***.***>
抄送: Thunpe ***@***.***>; Mention ***@***.***>
主题: Re: [Wilenty/7zOverlay] 64 bit program usage issues (Issue #2)


Hello @Thunpe<https://github.com/Thunpe>.
Sorry for late response, but now I have hard physical work, so I can check the messages only in the Sunday.

At the outset please edit first post and remove the email address from it, I have your email in my messages, so it's not need to be here.

Thank you for providing the excellent 7zOverlay.dll tool for free.
Thanks!
This version is only applicable to 32-bit program calls，Not applicable for 64 bit program calls.
Yes, for free I share only the 32-bit of this dll, especially for the InnoSetup based installers, because it has the lack of extracting other archives, excluding itself.

Consult if there is an x64 (64 bit) version available for 7z.dll，If there is (how much donation is required to obtain the x64 (64 bit) version suitable for 7z.dll).
(Probably) I have the 64-bit somewhere on the main computer, but it's old and it should be updated to the latest version, which takes the time.

If you saw, or not, I disabled all donation pages, because I don't have a time to check and share my products in the week. Also I need some free time time in the weekend to get the rest.

So, maybe for first we can talk here how much you would pay for the 64-bit version of 7zOverlay.dll? Then I will know if I should focus to update this dll to the latest version.
And I don't know if you want to use this dll personally or in corporation/office?

Greetings.
Wilenty

―

**Comment by Thunpe** [comment]
If there's no problem, please delete the reply from Github so that others don't come to me for this 7zOverlay.dll
________________________________
发件人: 岑 浩泉 ***@***.***>
发送时间: 2023年6月19日 15:03
收件人: Wilenty ***@***.***>; Wilenty/7zOverlay ***@***.***>; Wilenty/7zOverlay ***@***.***>
抄送: Mention ***@***.***>
主题: 答复: [Wilenty/7zOverlay] 64 bit program usage issues (Issue #2)

Hello, thank you for your reply
I plan to integrate this 7zOverlay.dll into a program for use, as there is no revenue source for this program.
DLLs can be encrypted and compressed before being built into the program. When called, memory runs without the need to decompress resources. This DLL will not be publicly shared.
Also, I don't know if it's possible to add a callback function to obtain the progress required.
In terms of donations: I wonder if 100 US dollars is possible
________________________________
发件人: Wilenty ***@***.***>
发送时间: 2023年6月19日 10:59
收件人: Wilenty/7zOverlay ***@***.***>
抄送: Thunpe ***@***.***>; Mention ***@***.***>
主题: Re: [Wilenty/7zOverlay] 64 bit program usage issues (Issue #2)


Hello @Thunpe<https://github.com/Thunpe>.
Sorry for late response, but now I have hard physical work, so I can check the messages only in the Sunday.

At the outset please edit first post and remove the email address from it, I have your email in my messages, so it's not need to be here.

Thank you for providing the excellent 7zOverlay.dll tool for free.
Thanks!
This version is only applicable to 32-bit program calls，Not applicable for 64 bit program calls.
Yes, for free I share only the 32-bit of this dll, especially for the InnoSetup based installers, because it has the lack of extracting other archives, excluding itself.

Consult if there is an x64 (64 bit) version available for 7z.dll，If there is (how much donation is required to obtain the x64 (64 bit) version suitable for 7z.dll).
(Probably) I have the 64-bit somewhere on the main computer, but it's old and it should be updated to the latest version, which takes the time.

If you saw, or not, I disabled all donation pages, because I don't have a time to check and share my products in the week. Also I need some free time time in the weekend to get the rest.

So, maybe for first we can talk here how much you would pay for the 64-bit version of 7zOverlay.dll? Then I will know if I should focus to update this dll to the latest version.
And I don't know if you want to use this dll personally or in corporation/office?

Greetings.
Wilenty

―

**Comment by Thunpe** [comment]
> 
Hello，Thank you for your reply

Is it okay to pay $100？ This DLL is for personal use，It will not be disclosed.
Can I add a callback function？Obtaining progress requires

**Comment by Wilenty** [comment]
Hello @Thunpe,
sorry for late response, but I had high fever (around 40C), and I've spend half of the day in the bed, now I am back from the "Hospital emergency ward".
I am going to be OK, but please don't "bump" me with too many messages - I will answer when I'll be on-line. :)

```Is it okay to pay $100？ This DLL is for personal use，It will not be disclosed.```
Yes, it's a very good support!
```Can I add a callback function？Obtaining progress requires```
No, you can't add a callback, because none of existing functions supports it in this dll, but I will have to check the source if I can add the callback Function.

To be honest, I waiting for the source of 7-zip in version 23.XX, to check what is changed there, because there are many good changes!

So, I will check in my free time, what I can do and let you know.

By the way, I deleted your first (original) post before edition that no one will write to you on this email address.

Greetings,
Wilenty

**Comment by Thunpe** [comment]
Save you rvaluable time，can add a callback function from the old 19.xx version。
Update to the latest version when there is free time in the future，In addition the 'l' parameter output message will not be displayed on a separate line.

**Comment by Thunpe** [comment]
How is the development progress of the 64-bit version of 7zOverlay

**Comment by Wilenty** [comment]
Hello @Thunpe,
sorry for late replay, but I have short time for myself because of the work...
So the work on 7zOverlay with callback going slowly...

But, I have a proposition for you, namely, in the weekend I will enable the Patreon support, you will pay half of the mentioned above price i.e. $50 and I will share for you current 64-bit version of 7zOverlay without the callback, so you will be able to work on your project right now.
But, when I will do the callback function at your request, you will pay second part via donation, and I will share for you updated 7zOverlay with callback.
Can be the deal like this?

There are many lines of code to review/change/check/etc., so...

Greetings,
Wilenty

**Comment by Thunpe** [comment]
No callback function，I am unable to use this DLL to complete the work。
How long will it take for 7zOverlay with callback functions to update support?

**Comment by Wilenty** [comment]
Hello @Thunpe,
sorry for late response.

I am working on the progress of operations (packing/unpacking) as a CallBack for external programs, but I don't know how much time it will take...

Please give me one week, and in next weekend I will write to you information if it's done or not.
And if it will not be done - you will decide if you want to wait for it longer, or not.

Greetings,
Wilenty

**Comment by Wilenty** [comment]
Hello @Thunpe,
I already created the 7zOverlay with CallBack procedure, and shared it (x86 for test) here: https://github.com/Wilenty/7zOverlay/tree/master/BETAwithCallBack

Please check it and let me know if it's okay for you?

Greetings,
Wilenty

**Comment by Thunpe** [comment]
Hello @Wilenty.
Sorry for the delayed response due to work reasons,
I don't know how to use the fourth parameter of CommandFor7zipWithCallBackkW，When the fourth parameter is set to 0, the work can be completed.
I don't know how the callback task works.

Feedback on a problem: compressing documents - mx0 only takes more than 50% more time to store without compression than 7z.exe.
Besides, can we have a private chat

**Comment by Wilenty** [comment]
Hello @Thunpe,
I am sorry, but currently I am outside the home.

I see you are C/C++ programmer, because only the x86 (32-bit) version does not work correctly in C/C++. And I have no idea why...
I checked new 7zOverlay.dll with CallBack procedure in both architectures (x64/x86), and I saw the problem with file number only in 32-bit VS2015CE, the x64 version in C/C++ works okay.

If you check compiled Delphi example, you will see the file number in CallBack procedure without the need of changing parameters.
For example:

![Delphi01](https://github.com/Wilenty/7zOverlay/assets/61757638/68be18f6-409e-4490-bc36-58a374a4d3a3)

![Delphi02](https://github.com/Wilenty/7zOverlay/assets/61757638/104b9694-404c-4f29-8df1-c2ce02a71e5e)

I have my own Discord, so if you want to come, please join here:
https://discord.com/invite/dED3hNQ

My Discord it's a bit protected that new users don't see current users, but when you come and I will be on-line, I will add you to the members list, an then we can talk privately on DM (PM).

Greetings,
Wilenty

**Comment by Wilenty** [comment]
Hello @Thunpe,
I have to ask you if you joined my Discord, and which one login is yours, because I see two:
`Thunpe#8966`
`Thunpe#5651`
So, when you tell me which one is yours - then I will add you. :)

Greetings,
Wilenty

**Comment by Thunpe** [comment]
Thunpe#5651

**Comment by Thunpe** [comment]
Thunpe#5651
