### ISSUE TITLE
7-Zip-X64-X86-with-Extracting-NSIS-script

### ISSUE THREAD

**Issue by TaciturnShadow** [Wilenty/7zOverlay#3]
Hello. I apologize for being offtopic in this repository, but I did not find a normal way to write directly.
Your fork of 7-Zip is really great, I take great pleasure in using it. But recently a new version of 7-Zip has been released, and the repository is archived. Can you please tell me if there is any chance you will update your fork to 23.01?

**Comment by Wilenty** [comment]
Hello @TaciturnShadow,
no problem, you can always ask, even in different repository... :)

Thank you for good words about my work!

```
Can you please tell me if there is any chance you will update your fork to 23.01?
```
The problem is that I've spend many time to "serve users wishes", but to be honest they won't support me, that I can work only on this. So now I have hard physical work, and I disabled all support pages (I write it once again), if you saw it or not.

If you wish to support me, I can do the 7-ZIP v23.01 for you with all of the things mentioned in that repository.
If you want, I will enable the ko-fi support, for example, and then I will starts working on 7-ZIP.

Greetings,
Wilenty

**Comment by TaciturnShadow** [comment]
> If you wish to support me, I can do the 7-ZIP v23.01 for you with all of the things mentioned in that repository.

It will probably be too high a price for me, but still I ask - how much will it cost?

**Comment by Wilenty** [comment]
Hello @TaciturnShadow,
sorry for late response.

```but still I ask - how much will it cost?```
Say your price, and I am sure we can make a deal.

Greetings,
Wilenty

**Comment by TaciturnShadow** [comment]
I found https://github.com/myfreeer/7z-build-nsis and it's enough.
